services:
  # Base de datos Redis para Celery
  redis:
    image: redis:alpine
    container_name: redis_db
    networks:
      - internal

  # API de Python (FastAPI)
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: fastapi_ml
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - internal

  # Worker de Celery para manejo de colas con 5 concurrentes
  worker:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A config.celery_config.celery_app worker --loglevel=info --concurrency=5
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/1
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - api
    networks:
      - internal

  # Gateway de Go
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - api
    expose:
      - 8080
    networks:
      - internal

networks:
  internal:
    driver: bridge